name: news_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  
  firebase_auth: ^4.4.1
  firebase_core: ^2.9.0
  flutter_riverpod: ^2.3.4
  http: ^0.13.5
  go_router: ^6.5.6
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.5
  shimmer: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  freezed_annotation: ^2.2.0 #
  
  riverpod_annotation: ^2.0.1
  shared_preferences: ^2.1.0
  google_sign_in: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5
  build_runner: ^2.3.0 #
  freezed: ^2.3.2 #

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
